### ISSUE TITLE
Should we have separate packages for different sources?

### ISSUE THREAD

**Issue by rofr** [rofr/Fig#10]
Or just shove it all into a single project/package.

Currently, the AppSettingsXml source is in a separate project (and separate nuget package).
The reason is to minimize dependencies in the core package. In this case System.Configuration is the additional dependency.

All the other sources are in the core project: ini, json,env vars, command line. The json source uses the new System.Json so to follow the pattern this should have gone to a separate project as well.

What's your opinion here @myty ?

**Comment by myty** [comment]
My tendency is to lean towards one package for simplicity's sake but I really like the idea of not pulling in more dependencies than what is needed.  I'd also suggest that as far as nuget packages go, having a separate package per configuration source but also having an "All Sources" package.

**Comment by rofr** [comment]
Some of the sources do not require any additional dependencies so there is little value in putting them in separate projects / packages.  So Environment vars, ini-files and CommandLineArgs sources stay in the core package.

The sources that have additional deps are:
* AppSettingsJsonSource (depends on System.Json)
* AppSettingsXmlSettingsSource (depends on System.Configuration)

So I suggest the following nuget packages:

`Fig.All` (this is a bundle which includes all the other packages)
`Fig` (the core library and with the 3 built in sources)
`Fig.AppSettingsXml`
`Fig.AppSettingsJson`

**Comment by rofr** [comment]
Done
