### ISSUE TITLE
Environment qualifiers in JSON files

### ISSUE THREAD

**Issue by rofr** [rofr/Fig#23]
The environment qualier is appended using a ':' as separator. This works in INI-files and XML files but perhaps not appSettings.json because ':' is used as a path separator in JSON. I think it could be put it inside the attribute name like this:

```JSON
{
   "MySetting" : 42,
   "MySetting:PROD" : 43
}
```
So the question is: Does the above already work and is it a good approach? I think the colon inside the attribute might cause some confusion.

A simple unit test answer the 'does it work' question. One thing that does not work though, if we decide to go this path, is having the qualifier above a nested object. (see #22 )

```JSON
{
    "MySetting:PROD" : {
      "a":1,
     "b":2
    }
} 
```
this would translate into keys:
MySetting:PROD.a
MySetting:PROD.b

It seems like a rewrite of each key where the qualifier is moved to the the end would do trick. Actually, we could use the rewrite hack for INI files (#22 again) and other hierarchical sources as a postprocessing step on the settings dictionaries.

**Comment by myty** [comment]
Are you saying that the keys for this
```c#
{
    "MySetting:PROD" : {
      "a":1,
     "b":2
    }
} 
```

would be like this?
```c#
MySetting.a:PROD
MySetting.b:PROD
```

I think that's a good idea.

**Comment by rofr** [comment]
Yes, exactly. I'll take this one then!

**Comment by rofr** [comment]
Done
