### ISSUE TITLE
Support for arrays

### ISSUE THREAD

**Issue by rofr** [rofr/Fig#27]
An array in JSON translates into keys with numeric indexes, ie:
```json
"brokers" : ["10.0.0.1", "10.0.0.2"]
````
will translate into the key/value pairs:

```
brokers.0=10.0.0.1
brokers.1=10.0.0.2
```

When we retrieve we want to be able to convert to array, ie:

```c#
var brokers = settings.Get<string[]>("brokers");
```
and a typed settings class:

```c#
class MySettings
{
   public string[] Brokers => Get<string[]>();
}
```

**Comment by rofr** [comment]
And if the setting is a single value without indicies try to interpret as a comma-separated list. So:
```ini
brokers=10.0.0.1,10.0.0.2
```
will work as well

**Comment by Venom0us** [comment]
@rofr Can be closed I guess?
