### ISSUE TITLE
Add TryGetValue<T> and Get<T> to the IProvider interface

### ISSUE THREAD

**Issue by myty** [rofr/Fig#3]
What are your thoughts on adding these to the `IProvider` interface?

```csharp
bool TryGetValue<T>(string key, out T value);
T Get<T>(string key);
```

If it's ok with you, I can add them along with some tests.

**Comment by rofr** [comment]
The IProvider interface is gone, we now have SettingsSource and ISettingsSource instead which have an entirely different interface...
