### ISSUE TITLE
CompositeProvider - TryGet will always return false

### ISSUE THREAD

**Issue by myty** [rofr/Fig#4]
A bug with CompositeProvider.TryGet that will always return false.  When this is fixed we should also attach some tests to the PR to handle all the scenarios.
https://github.com/rofr/Fig/blob/9e5b91d5fa1ae38829a2811f5dac578c7cbaec35/Fig.Core/CompositeProvider.cs#L31-L44

**Comment by rofr** [comment]
CompositeProvider is gone too, so this issue is now also obsolete. Sorry :/
