### ISSUE TITLE
Add more string conversion tests

### ISSUE THREAD

**Issue by rofr** [rofr/Fig#5]
Add more tests to StringConversionTests for various types:
- [ ] float
- [ ] short
- [ ] byte
- [ ] ushort
- [ ] uint
- [ ] long
- [ ] ulong
- [ ] Enumerations

What else?

**Comment by myty** [comment]
How about `DateTime` and `TimeSpan`?

**Comment by rofr** [comment]
done,  see 5ccbf5a
